const PostsArray = [
    {
        id: 1,
        image: '/images/placesFirst.jpg',
        categories: 'Places',
        description: 'Nam tincidunt metus',
        photo: '/images/author.png',
        name: 'Muffin Group',
        date: 'October 23,2019',
    },
    {
        id: 2,
        image: '/images/placesSecond.jpg',
        categories: 'Places',
        description: 'Fusce sagittis risus a urna',
        photo: '/images/author.png',
        name: 'Muffin Group',
        date: 'October 23,2019',
    },
    {
        id: 3,
        image: '/images/placesThird.jpg',
        categories: 'Places',
        description: 'Vestibulum sollicitudin est',
        photo: '/images/author.png',
        name: 'Muffin Group',
        date: 'October 23,2019',
    },
    // {
    //     id: 4,
    //     image: '/images/guidesThird.jpg',
    //     categories: 'Guides',
    //     description: 'Ut sodales nunc eu',
    //     photo: '/images/author.png',
    //     name: 'Muffin Group',
    //     date: 'October 23,2019',
    // },
    // {
    //     id: 5,
    //     image: '/images/guidesThird.jpg',
    //     categories: 'Guides',
    //     description: 'Maecenas congue augue',
    //     photo: '/images/author.png',
    //     name: 'Muffin Group',
    //     date: 'October 23,2019',
    // },
    // {
    //     id: 6,
    //     image: '/images/guidesThird.jpg',
    //     categories: 'Guides',
    //     description: 'Aliquam mollis purus',
    //     photo: '/images/author.png',
    //     name: 'Muffin Group',
    //     date: 'October 23,2019',
    // },
]
export default PostsArray
